#!/usr/bin/env python3
"""
ボットの鍵生成スクリプト
100体のボットのnsecを生成して.env.keysに保存
"""
from pathlib import Path

from nostr_sdk import Keys


def generate_bot_keys(count: int = 100) -> None:
    print(f"Generating keys for {count} bots...")

    env_keys_file = Path(".env.keys")

    lines = ["# Bot keys - NEVER commit this file to git!\n"]
    lines.append("# Generated by scripts/generate_keys.py\n\n")

    for i in range(1, count + 1):
        # 新しい鍵ペアを生成
        keys = Keys.generate()

        bot_id = f"{i:03d}"
        pubkey = keys.public_key().to_hex()
        nsec = keys.secret_key().to_bech32()

        lines.append(f"# Bot {bot_id}\n")
        lines.append(f"BOT_{bot_id}_PUBKEY={pubkey}\n")
        lines.append(f"BOT_{bot_id}_NSEC={nsec}\n\n")

        if i % 10 == 0:
            print(f"Generated {i}/{count} keys...")

    # .env.keysに保存
    with open(env_keys_file, "w") as f:
        f.writelines(lines)

    print(f"\n✅ Successfully generated {count} bot keys!")
    print(f"📁 Saved to: {env_keys_file}")
    print(f"\n⚠️  IMPORTANT: Keep {env_keys_file} secure and NEVER commit it to git!")
    print("Add to your .gitignore if not already present.")


if __name__ == "__main__":
    generate_bot_keys()
